# Generated by Django 4.2.3 on 2023-07-31 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[(None, 'Не указано'), ('OPD', 'Раз в день'), ('OPW', 'Раз в неделю'), ('OPM', 'Раз в месяц')], default=None, max_length=3, verbose_name='Периодичность')),
                ('sending_status', models.CharField(choices=[(None, 'Не указано'), ('created', 'Создана'), ('active', 'Запущена'), ('closed', 'Завершена')], default=None, max_length=7, verbose_name='Статус отправки')),
                ('message_title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('message_content', models.TextField(verbose_name='Содержание')),
                ('customers', models.ManyToManyField(to='mailing.customer', verbose_name='Клиенты')),
                ('mailing_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель рассылки')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылок',
                'ordering': ('sending_status',),
            },
        ),
    ]
